[book]
authors = ["momentmaker"]
language = "en"
multilingual = false
src = "src"
title = "walk ⬡ talk ⬡ meditate"
description = "taking pilgrimage in a new light the open-source way"
keywords = "pilgrimage, meditation, spiritual"

[output.html]
git-repository-url = "https://github.com/momentmaker/walk-talk-meditate"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/momentmaker/walk-talk-meditate/discussions"
