[book]
authors = ["momentmaker"]
language = "en"
multilingual = false
src = "src"
title = "walk ⬡ talk ⬡ meditate"
description = "taking pilgrimage in a new light the open-source way"
keywords = "pilgrimage, meditation, spiritual"
