baseURL = "https://pilgrimag.es"
theme = 'hugo-bearblog'
title = "walk ⬡ talk ⬡ meditate"
author = "mm"
copyright = "copy it"
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "taking pilgrimage in a new light the open-source way"
  favicon = "images/favicon.png"
  images = ["images/share.jpg"]
  title = "walk ⬡ talk ⬡ meditate"
  hideMadeWithLine = true
